### ISSUE TITLE
Failed to apply plugin

### ISSUE THREAD

**Issue by gfiedler** [EndlessCodeGroup/BukkitGradle#19]
The following `build.gradle`

```
plugins {
    id "ru.endlesscode.bukkitgradle" version "0.8.0"
}
 
dependencies {
    compileOnly bukkit() 
}
```

failed with

```
BuildTools not found on path: '***/build/buildtools/BuildTools.jar'
BuildTools directory should contains BuildTools.jar file.

FAILURE: Build failed with an exception.

* Where:
Build file '***/build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'ru.endlesscode.bukkitgradle', version: '0.8.0']
> Failed to apply plugin [id 'ru.endlesscode.bukkitgradle']
   > No signature of method: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated.ext() is applicable for argument types: (ru.endlesscode.bukkitgradle.util.Dependencies$_addExtensions_closure2) values: [ru.endlesscode.bukkitgradle.util.Dependencies$_addExtensions_closure2@4cb45acd]
     Possible solutions: wait(), any(), wait(long), any(groovy.lang.Closure), with(groovy.lang.Closure), each(groovy.lang.Closure)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

CONFIGURE FAILED
```

Gradle version: 3.2

**Comment by osipxd** [comment]
Hello!
Try to update Gradle.
If problem not gone, run task with `--stacktrace` and paste stacktrace here.

**Comment by gfiedler** [comment]
Thank you! Using Gradle 4.x solved the issue.

Now I get another error:

```
$ gradle runServer
...
:bukkit-sample-plugin:runServer
Running script built!
Starting Server...
:bukkit-sample-plugin:runServer FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bukkit-sample-plugin:runServer'.
> java.lang.ArrayStoreException (no error message)
...
Caused by: java.lang.ArrayStoreException
	at java_lang_ProcessBuilder$start$1.call(Unknown Source)
	at ru.endlesscode.bukkitgradle.task.RunServer.runScript(RunServer.groovy:34)
	at ru.endlesscode.bukkitgradle.task.RunServer$runScript.callCurrent(Unknown Source)
	at ru.endlesscode.bukkitgradle.task.RunServer.runServer(RunServer.groovy:19)
...
```

I found out that a (non-executable) file `build/server/1.12.2/start.sh` is created and when I execute that file with

```
cd build/server/1.12.2 && sh start.sh
```

Bukkit server will be successfully started. But Gradle task 'runServer' doesn't work as documented.

**Comment by gfiedler** [comment]
Thank you! Can you please deploy a version 0.8.1 with this fix?

**Comment by osipxd** [comment]
Yes, I'll release it soon
